title: Martin Schmidt
logo: "/images/PhotoMartinSchmidt.jpg?raw=true"
description: >
  <br><br>
  I studied financial and actuarial mathematics at the Vienna University of Technology and
  have been working as a Credit Risk Manager in the banking sector in Austria for more than
  3 years, where I use my profound quantitative/programming skills in a profitable way for
  the benefit of my company.
  My quick comprehension and high willingness to learn characterize me as a person.
  <br><br>
  <a href="https://www.linkedin.com/in/martschm/">View My LinkedIn Profile</a>  
theme: jekyll-theme-minimal
