title: DI Martin Schmidt
logo: "/images/Picture_Coding.jpg?raw=true"
description: >
  <br>
  I hold a Master's degree in Financial and Actuarial Mathematics from the Vienna University of Technology 
  (graduation with highest distinction) and have been working as a Quantitative Credit Risk Manager within 
  an international banking group in Austria for almost 4 years. I have excellent programming and database 
  (Python, R, SAS, SQL) as well as statistical/mathematical skills and gained hands-on machine learning 
  experience during various Data Science Hackathons (most recent: Winner of the Coding Challenge on Risk Management 
  hosted by the European Central Bank)
  
theme: jekyll-theme-minimal
